# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/jerry/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake

# The command to remove a file.
RM = /Users/jerry/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jerry/Projects/jetpackrunner-master/JetpackRunner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jerry/Projects/jetpackrunner-master/JetpackRunner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/Users/jerry/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/Users/jerry/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cpack --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Users/jerry/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"bin\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Users/jerry/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Users/jerry/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Users/jerry/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Users/jerry/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Users/jerry/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Users/jerry/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jerry/Projects/jetpackrunner-master/JetpackRunner/CMakeFiles /Users/jerry/Projects/jetpackrunner-master/JetpackRunner//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jerry/Projects/jetpackrunner-master/JetpackRunner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named JetpackRunner

# Build rule for target.
JetpackRunner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JetpackRunner
.PHONY : JetpackRunner

# fast build rule for target.
JetpackRunner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/build
.PHONY : JetpackRunner/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build.make _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named sfml-window

# Build rule for target.
sfml-window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-window
.PHONY : sfml-window

# fast build rule for target.
sfml-window/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build.make _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build
.PHONY : sfml-window/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build.make _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-graphics

# Build rule for target.
sfml-graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-graphics
.PHONY : sfml-graphics

# fast build rule for target.
sfml-graphics/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build.make _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build
.PHONY : sfml-graphics/fast

#=============================================================================
# Target rules for targets named sfml-audio

# Build rule for target.
sfml-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-audio
.PHONY : sfml-audio

# fast build rule for target.
sfml-audio/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build.make _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build
.PHONY : sfml-audio/fast

Source/Entity.o: Source/Entity.cpp.o
.PHONY : Source/Entity.o

# target to build an object file
Source/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Entity.cpp.o
.PHONY : Source/Entity.cpp.o

Source/Entity.i: Source/Entity.cpp.i
.PHONY : Source/Entity.i

# target to preprocess a source file
Source/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Entity.cpp.i
.PHONY : Source/Entity.cpp.i

Source/Entity.s: Source/Entity.cpp.s
.PHONY : Source/Entity.s

# target to generate assembly for a file
Source/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Entity.cpp.s
.PHONY : Source/Entity.cpp.s

Source/Game.o: Source/Game.cpp.o
.PHONY : Source/Game.o

# target to build an object file
Source/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Game.cpp.o
.PHONY : Source/Game.cpp.o

Source/Game.i: Source/Game.cpp.i
.PHONY : Source/Game.i

# target to preprocess a source file
Source/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Game.cpp.i
.PHONY : Source/Game.cpp.i

Source/Game.s: Source/Game.cpp.s
.PHONY : Source/Game.s

# target to generate assembly for a file
Source/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Game.cpp.s
.PHONY : Source/Game.cpp.s

Source/Items.o: Source/Items.cpp.o
.PHONY : Source/Items.o

# target to build an object file
Source/Items.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Items.cpp.o
.PHONY : Source/Items.cpp.o

Source/Items.i: Source/Items.cpp.i
.PHONY : Source/Items.i

# target to preprocess a source file
Source/Items.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Items.cpp.i
.PHONY : Source/Items.cpp.i

Source/Items.s: Source/Items.cpp.s
.PHONY : Source/Items.s

# target to generate assembly for a file
Source/Items.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Items.cpp.s
.PHONY : Source/Items.cpp.s

Source/Player.o: Source/Player.cpp.o
.PHONY : Source/Player.o

# target to build an object file
Source/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Player.cpp.o
.PHONY : Source/Player.cpp.o

Source/Player.i: Source/Player.cpp.i
.PHONY : Source/Player.i

# target to preprocess a source file
Source/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Player.cpp.i
.PHONY : Source/Player.cpp.i

Source/Player.s: Source/Player.cpp.s
.PHONY : Source/Player.s

# target to generate assembly for a file
Source/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Player.cpp.s
.PHONY : Source/Player.cpp.s

Source/Zapper.o: Source/Zapper.cpp.o
.PHONY : Source/Zapper.o

# target to build an object file
Source/Zapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Zapper.cpp.o
.PHONY : Source/Zapper.cpp.o

Source/Zapper.i: Source/Zapper.cpp.i
.PHONY : Source/Zapper.i

# target to preprocess a source file
Source/Zapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Zapper.cpp.i
.PHONY : Source/Zapper.cpp.i

Source/Zapper.s: Source/Zapper.cpp.s
.PHONY : Source/Zapper.s

# target to generate assembly for a file
Source/Zapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/Zapper.cpp.s
.PHONY : Source/Zapper.cpp.s

Source/main.o: Source/main.cpp.o
.PHONY : Source/main.o

# target to build an object file
Source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/main.cpp.o
.PHONY : Source/main.cpp.o

Source/main.i: Source/main.cpp.i
.PHONY : Source/main.i

# target to preprocess a source file
Source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/main.cpp.i
.PHONY : Source/main.cpp.i

Source/main.s: Source/main.cpp.s
.PHONY : Source/main.s

# target to generate assembly for a file
Source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JetpackRunner.dir/build.make CMakeFiles/JetpackRunner.dir/Source/main.cpp.s
.PHONY : Source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... JetpackRunner"
	@echo "... sfml-audio"
	@echo "... sfml-graphics"
	@echo "... sfml-network"
	@echo "... sfml-system"
	@echo "... sfml-window"
	@echo "... Source/Entity.o"
	@echo "... Source/Entity.i"
	@echo "... Source/Entity.s"
	@echo "... Source/Game.o"
	@echo "... Source/Game.i"
	@echo "... Source/Game.s"
	@echo "... Source/Items.o"
	@echo "... Source/Items.i"
	@echo "... Source/Items.s"
	@echo "... Source/Player.o"
	@echo "... Source/Player.i"
	@echo "... Source/Player.s"
	@echo "... Source/Zapper.o"
	@echo "... Source/Zapper.i"
	@echo "... Source/Zapper.s"
	@echo "... Source/main.o"
	@echo "... Source/main.i"
	@echo "... Source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

